version: "3.3"

services:
  plc-bridge:
    image: agrisphere-plc:latest
    build: .
    network_mode: host
    env_file:
      - .env
    restart: unless-stopped
    privileged: true
    pid: host
    volumes:
      - /usr/bin/piTest:/usr/bin/piTest
      - /usr/lib:/usr/lib
      - /dev:/dev
      - /var/run/piserial:/var/run/piserial
